name: Linux vcpkg with GitHub Packages Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  packages: write

env:
  USERNAME: ${{ github.repository_owner }}
  VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Checkout vcpkg
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg
        path: vcpkg
    
    - name: Install mono (required for nuget.exe)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete
    
    - name: Bootstrap vcpkg
      shell: bash
      run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
    
    - name: Add NuGet sources
      shell: bash
      run: |
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          sources add \
          -Source "${{ env.FEED_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ env.USERNAME }}" \
          -Password "${{ secrets.GITHUB_TOKEN }}"
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -Source "${{ env.FEED_URL }}"
    
    - name: Install vcpkg packages from manifest
      shell: bash
      run: |
        # Install packages defined in vcpkg.json (manifest mode)
        echo "Installing packages from vcpkg.json manifest..."
        ${{ env.VCPKG_EXE }} install --triplet x64-linux
        echo "Binary caching is enabled: $VCPKG_BINARY_SOURCES"

